CapaAdministrador/Controllers/MantenedorController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;

namespace CapaAdministrador.Controllers
{
    [Authorize]
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marca()
        {
            return View();
        }
        public ActionResult Producto()
        {
            return View();
        }

        #region CATEGORIA

        [HttpGet]
        public JsonResult ListarCategoria()
        {
            List<Categoria> olista = new List<Categoria>();
            olista = new CN_Categoria().listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdCategoria == 0)
            {
                resultado = new CN_Categoria().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Categoria().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {

            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region MARCA

        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<Marca> olista = new List<Marca>();
            olista = new CN_Marca().listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(Marca objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdMarca == 0)
            {
                resultado = new CN_Marca().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {

            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Producto

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> olista = new List<Producto>();
            olista = new CN_Producto().listar();

            return Json(new { data = olista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(string objeto, HttpPostedFileBase archivoImagen)
        {
            object resultado;
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool guardar_imagen_exito = true;

            Producto oproducto = new Producto();
            oproducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio;
            if (decimal.TryParse(oproducto.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-CO"), out precio))
            {

                oproducto.Precio = precio;
            }
            else
            {

                return Json(new { operacion_exitosa = false, mensaje = "El formato del precio debe ser en ##.##" }, JsonRequestBehavior.AllowGet);
            }

            if (oproducto.IdProducto == 0)
            {
                int idProductoGenerado = new CN_Producto().Registrar(oproducto, out mensaje);
                if (idProductoGenerado != 0)
                {
                    oproducto.IdProducto = idProductoGenerado;
                }
                else
                {
                    operacion_exitosa = new CN_Producto().Editar(oproducto, out mensaje);
                }
            }


            if (operacion_exitosa)
            {

                if (archivoImagen != null)
                {

                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoImagen.FileName);
                    string nombre_imagen = string.Concat(oproducto.IdProducto.ToString(), extension);

                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));
                    }
                    catch (Exception ex)
                    {
                        string msg = ex.Message;
                        guardar_imagen_exito = false;
                    }

                    if (guardar_imagen_exito)
                    {
                        oproducto.RutaImagen = ruta_guardar;
                        oproducto.NombreImagen = nombre_imagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oproducto, out mensaje);
                    }
                    else
                    {

                        mensaje = "Se guardo el producto pero hubo un problema con la imagen";
                    }


                }
            }
            return Json(new { operacion_exitosa = operacion_exitosa,idGenerado= oproducto.IdProducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult ImagenProducto(int id) {

            bool conversion;
            Producto oproducto = new CN_Producto().listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oproducto.RutaImagen, oproducto.NombreImagen), out conversion);

            return Json(new
            {

                conversion = conversion,
                textoBase64 = textoBase64,
                extension = Path.GetExtension(oproducto.NombreImagen)

            },
            JsonRequestBehavior.AllowGet

            );
        }


        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {

            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

CapaAdministrador/Views/Mantenedor/Categoria.cshtml

@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categoria</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i>Lista de Categoria
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />

                <div class="row g-1">

                    <div class="col-sm-6">
                        <label for="txtdescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtdescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert" style="display:none;">

                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

         var tabladata;
         var filaSeleccionada

                     tabladata = $("#tabla").DataTable({
                    responsive: true,
                    ordering: false,
                    "ajax": {
                        url: '@Url.Action("ListarCategoria", "Mantenedor")',
                        type: "GET",
                        dataType: "json"
                    },
                    "columns": [
                        { "data": "Descripcion" },
                       {
                            "data": "Activo", "render": function (valor) {

                                if (valor) {
                                    return '<span class="badge bg-success">Si</span>'
                                } else {
                                    return '<span class="badge bg-danger">No</span>'
                                }
                            }
                        },
                        {
                            "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                                              '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                            "orderable": false,
                            "searchable": false,
                            "width": "90px"
                        }
                         ],
                         "language": {
                             "url": "https://cdn.datatables.net/plug-ins/2.1.8/i18n/es-ES.json"
                         }
                        });


        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtdescripcion").val("");
            $("#cboactivo").val(1);

            $("#mensajeError").hide();
            if (json != null) {

                $("#txtid").val(json.IdCategoria);
                $("#txtdescripcion").val(json.Descripcion);
                $("#cboactivo").val(json.Activo == true ? 1:0 );

            }
            $("#FormModal").modal("show");
        }

        //editar
        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();
            abrirModal(data)
        })

        //eliminar
        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var categoriaseleccionada = $(this).closest("tr");

            var data = tabladata.row(categoriaseleccionada).data();

            swal({
                title: "Estas seguro?",
                text: "¿Deseas eliminar la categoria?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                    jQuery.ajax({
                        url: '@Url.Action("EliminarCategoria", "Mantenedor")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdCategoria }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {
                                tabladata.row(categoriaseleccionada).remove().draw();
                            } else {
                                swal("No se pudo eliminar el usuario", data.mensaje, "error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }

                    });
             })
        })

        function Guardar()
        {

                      var Categoria = {

                          IdCategoria: $("#txtid").val(),
                          Descripcion: $("#txtdescripcion").val(),
                          Activo: $("#cboactivo").val() == 1 ? true : false,

                      }

                      jQuery.ajax({
                          url: '@Url.Action("GuardarCategoria", "Mantenedor")',
                          type: "POST",
                          data: JSON.stringify({ objeto: Categoria }),
                          dataType: "json",
                          contentType: "application/json; charset=utf-8",
                          success: function (data)
                          {

                              $(".modal-body").LoadingOverlay("hide");


                              if (Categoria.IdCategoria == 0) {

                                  if (data.resultado != 0) {

                                      Categoria.IdCategoria = data.resultado;
                                      tabladata.row.add(Categoria).draw(false);
                                      $('#FormModal').modal('hide');
                                  } else {
                                      $("#mensajeError").text(data.mensaje);
                                      $('#mensajeError').show();
                                  }
                              }

                              else {

                                  if (data.resultado) {
                                      tabladata.row(filaSeleccionada).data(Categoria).draw(false);
                                      filaSeleccionada = null;
                                      $('#FormModal').modal('hide');
                                  } else {
                                      $("#mensajeError").text(data.mensaje);
                                      $('#mensajeError').show();
                                  }
                              }
                          },
                          error: function (error) {
                              $(".modal-body").LoadingOverlay("hide");
                              $("#mensajeError").text("Error Ajax");
                              $("#mensajeError").show();
                          },
                          beforeSend: function (){
                              $(".modal-body").LoadingOverlay("show", {
                                  imageResizeFactor: 2,
                                  text: "Cargando...",
                                  size: 14
                              })
                          }
                      });

      }


    </script>
}


CapaAdministrador/Views/Mantenedor/Marca.cshtml

@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Marca</li>
</ol>

<div class="card">
    <div class="card-header">
        <i class="fas fa-users me-1"></i>Lista de Marca
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Crear Nuevo</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width: 100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header  bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />

                <div class="row g-1">

                    <div class="col-sm-6">
                        <label for="txtMarca" class="form-label">Marca</label>
                        <input type="text" class="form-control" id="txtMarca" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>

                </div>

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert" style="display:none;">

                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

         var tabladata;
         var filaSeleccionada

                     tabladata = $("#tabla").DataTable({
                    responsive: true,
                    ordering: false,
                    "ajax": {
                        url: '@Url.Action("ListarMarca", "Mantenedor")',
                        type: "GET",
                        dataType: "json"
                    },
                    "columns": [
                        { "data": "Descripcion" },
                       {
                            "data": "Activo", "render": function (valor) {

                                if (valor) {
                                    return '<span class="badge bg-success">Si</span>'
                                } else {
                                    return '<span class="badge bg-danger">No</span>'
                                }
                            }
                        },
                        {
                            "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                                              '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                            "orderable": false,
                            "searchable": false,
                            "width": "90px"
                        }
                         ],
                         "language": {
                             "url": "https://cdn.datatables.net/plug-ins/2.1.8/i18n/es-ES.json"
                         }
                        });


        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtMarca").val("");
            $("#cboactivo").val(1);

            $("#mensajeError").hide();
            if (json != null) {

                $("#txtid").val(json.IdMarca);
                $("#txtMarca").val(json.Descripcion);
                $("#cboactivo").val(json.Activo == true ? 1:0 );

            }
            $("#FormModal").modal("show");
        }

        //editar
        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();
            abrirModal(data)
        })

        //eliminar
        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var marcaseleccionada = $(this).closest("tr");

            var data = tabladata.row(marcaseleccionada).data();

            swal({
                title: "Estas seguro?",
                text: "¿Deseas eliminar la marca?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {
                    jQuery.ajax({
                        url: '@Url.Action("EliminarMarca", "Mantenedor")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdMarca }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {
                                tabladata.row(marcaseleccionada).remove().draw();
                            } else {
                                swal("No se pudo eliminar marca", data.mensaje, "error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }

                    });
             })
        })

        function Guardar()
        {

                      var Marca = {

                          IdMarca: $("#txtid").val(),
                          Descripcion: $("#txtMarca").val(),
                          Activo: $("#cboactivo").val() == 1 ? true : false,

                      }

                      jQuery.ajax({
                          url: '@Url.Action("GuardarMarca", "Mantenedor")',
                          type: "POST",
                          data: JSON.stringify({ objeto: Marca }),
                          dataType: "json",
                          contentType: "application/json; charset=utf-8",
                          success: function (data)
                          {

                              $(".modal-body").LoadingOverlay("hide");


                              if (Marca.IdMarca == 0) {

                                  if (data.resultado != 0) {

                                      Marca.IdMarca = data.resultado;
                                      tabladata.row.add(Marca).draw(false);
                                      $('#FormModal').modal('hide');
                                  } else {
                                      $("#mensajeError").text(data.mensaje);
                                      $('#mensajeError').show();
                                  }
                              }

                              else {

                                  if (data.resultado) {
                                      tabladata.row(filaSeleccionada).data(Marca).draw(false);
                                      filaSeleccionada = null;
                                      $('#FormModal').modal('hide');
                                  } else {
                                      $("#mensajeError").text(data.mensaje);
                                      $('#mensajeError').show();
                                  }
                              }
                          },
                          error: function (error) {
                              $(".modal-body").LoadingOverlay("hide");
                              $("#mensajeError").text("Error Ajax");
                              $("#mensajeError").show();
                          },
                          beforeSend: function (){
                              $(".modal-body").LoadingOverlay("show", {
                                  imageResizeFactor: 2,
                                  text: "Cargando...",
                                  size: 14
                              })
                          }
                      });

      }


    </script>
}